.TH CLI_NAME 1 "December 2023" "Your CLI Version"
.SH NAME
cli_name \- Your CLI description

.SH SYNOPSIS
.B cli_name
[\fIOPTION\fR]...

.SH DESCRIPTION
Describe your CLI and its options here.

.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Display help information.

.TP
\fB\-v\fR, \fB\-\-version\fR
Display the version.

.SH EXAMPLES
Show some usage examples.

.SH SEE ALSO
Mention related documentation.

.SH AUTHOR
Your Name <your.email@example.com>

.SH BUGS
Report bugs to <your.bug.tracker@example.com>